### ISSUE TITLE
broadcast

### ISSUE THREAD

**Issue by lineCode** [netskillzgh/rollo#10]
how to broadcast to all players

**Comment by netskillzgh** [comment]
Hi, store the active sessions in a hashmap and iterate ?

**Comment by lineCode** [comment]
Thank you. I'm a rust newer. I tried to use HashMap to save sessions but build with error. Haha, I'll learn rust doc again

**Comment by lineCode** [comment]
this is my test code, how can i use hashmap
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f56d983a9de6a315c7161a5b382bcb77

**Comment by netskillzgh** [comment]
It should works : https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c34fd866631d2e139c58e3c2cc7cd757

However the framework is a prototype for my game under Unity, it's not very stable.

**Comment by lineCode** [comment]
thank you very much. aha.., I'm very interested in rust, so try learn some about asynchronous network programming on rust
